
#matn = input()
#for index, s in enumerate(matn):
#    if matn.index(s)<index:
#        continue
#    else:
#        print(f"{s} harfi {matn.count(s)} marta qatnashgan")

matn=str(input())
a=matn.count('a')
b=matn.count('b')
c=matn.count('c')
d=matn.count('d')
e=matn.count('e')
f=matn.count('f')
g=matn.count('g')
h=matn.count('h')
ii=matn.count('i')
j=matn.count('j')
k=matn.count('k')
l=matn.count('l')
m=matn.count('m')
n=matn.count('n')
o=matn.count('o')
p=matn.count('p')
q=matn.count('q')
r=matn.count('r')
s=matn.count('s')
t=matn.count('t')
u=matn.count('u')
v=matn.count('v')
w=matn.count('w')
x=matn.count('x')
y=matn.count('y')
z=matn.count('z')
A=matn.count('A')
B=matn.count('B')
C=matn.count('C')
D=matn.count('D')
E=matn.count('E')
F=matn.count('F')
G=matn.count('G')
H=matn.count('H')
I=matn.count('I')
J=matn.count('J')
K=matn.count('K')
L=matn.count('L')
M=matn.count('M')
N=matn.count('N')
O=matn.count('O')
P=matn.count('P')
Q=matn.count('Q')
R=matn.count('R')
S=matn.count('S')
T=matn.count('T')
U=matn.count('U')
V=matn.count('V')
W=matn.count('W')
X=matn.count('X')
Y=matn.count('Y')
Z=matn.count('Z')
print(f"a {a}")
print(f"b {b}")
print(f"c {c}")
print(f"d {d}")
print(f"e {e}")
print(f"f {f}")
print(f"g {g}")
print(f"h {h}")
print(f"i {ii}")
print(f"j {j}")
print(f"k {k}")
print(f"l {l}")
print(f"m {m}")
print(f"n {n}")
print(f"o {o}")
print(f"p {p}")
print(f"q {q}")
print(f"r {r}")
print(f"s {s}")
print(f"t {t}")
print(f"u {u}")
print(f"v {v}")
print(f"w {w}")
print(f"x {x}")
print(f"y {y}")
print(f"z {z}")
print(f"A {A}")
print(f"B {B}")
print(f"C {C}")
print(f"D {D}")
print(f"E {E}")
print(f"F {F}")
print(f"G {G}")
print(f"H {H}")
print(f"I {I}")
print(f"J {J}")
print(f"K {K}")
print(f"L {L}")
print(f"M {M}")
print(f"N {N}")
print(f"O {O}")
print(f"P {P}")
print(f"Q {Q}")
print(f"R {R}")
print(f"S {S}")
print(f"T {T}")
print(f"U {U}")
print(f"V {V}")
print(f"W {W}")
print(f"X {X}")
print(f"Y {Y}")
print(f"Z {Z}")